name: setup gcc
description: installs dependencies and correct gcc version to build and test simeng

inputs:
  LLVM-VERSION: 
    required: true
  OS:
    required: true
  gcc-version:
    required: true

runs:
  using: 'composite'
  steps:
    #######################################
    # install dependencies required (cmake, etc)
    #######################################

    - name: install dependencies
      uses: ./.github/actions/setup_deps
      with:
        OS: ${{ inputs.OS }}

    - name: install cmake or restore from cache
      uses: ./.github/actions/setup_cmake
      with:
        OS: ${{ inputs.OS }}

    # running this prevents gcc-10 on ubuntu 20 from segfaulting in unit tests
    - if: ${{ inputs.gcc-version == 'gcc-10' }}
      name: install llvm
      shell: bash
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        ./llvm.sh ${{ inputs.LLVM-VERSION }}

    - name: install gcc
      shell: bash
      run: |
        apt-get -y install ${{ inputs.gcc-version }}
        apt-get -y install g++-$( echo ${{ inputs.gcc-version }} | cut -d '-' -f 2)
        apt update && apt upgrade -y
        echo "COMPILER_PATH=/usr/bin" >> $GITHUB_ENV
    #######################################
    - name: Build SimEng
      shell: bash
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DSIMENG_ENABLE_TESTS=ON -DSIMENG_OPTIMIZE=ON -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++

        cmake --build build -j $(nproc)

        sudo cmake --build build --target install