name: setup gcc
description: installs gcc of specified version

inputs:
  version:
    required: true

runs:
  using: 'composite'
  steps:

    - name: Cache GCC ${{ inputs.version }}
      id: cache-gcc
      uses: actions/cache@v3
      with:
        path: /usr/local/gcc-${{ inputs.version }}
        key: gcc-${{ inputs.version }}-${{ runner.os }}-${{ hashFiles('**/setup_gcc.sh') }}
        restore-keys: |
          gcc-${{ inputs.version }}-${{ runner.os }}-

    - name: install gcc ${{ inputs.version }}
      shell: bash
      run: |
        wget https://ftp.gnu.org/gnu/gcc/gcc-${{ inputs.version }}/gcc-${{ inputs.version }}.tar.gz > /dev/null 2>&1
        
        tar -xvf gcc-${{ inputs.version }}.tar.gz > /dev/null 2>&1

        pwd | ls

        cd gcc-${{ inputs.version }}

        ./contrib/download_prerequisites > /dev/null
        ./configure --enable-languages=c,c++ --disable-multilib --with-system-zlib --prefix=~/usr/local/gcc-${{ inputs.version }}
        
      # make -j15
      # make install
