name: setup gcc
description: installs gcc of specified version

inputs:
  version:
    required: true

runs:
  using: 'composite'
  steps:
  
    - name: install gcc ${{ inputs.version }} and makes
      runs: |
        wget https://ftp.gnu.org/gnu/gcc/gcc-${{ inputs.version }}/gcc-${{ inputs.version }}.tar.gz > /dev/null 2>&1
        
        tar -xvf gcc-${{ inputs.version }}.tar.gz > /dev/null 2>&1
        cd gcc-${{ inputs.version }}

        ./contrib/download_prerequisites > /dev/null
        ./configure --enable-languages=c,c++ --disable-multilib --with-system-zlib --prefix=/usr/local/gcc${{ inputs.version }}

        make -j15
        make install
