name: setup gcc
description: installs gcc of specified version

inputs:
  OS: 
    required: true
  gcc-version:
    required: true

runs:
  using: 'composite'
  steps:

    # - name: Cache GCC ${{ inputs.gcc-version }}
    #   id: cache-gcc
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/usr/local/gcc-${{ inputs.gcc-version }}
    #     key: gcc-${{ inputs.gcc-version }}-${{ inputs.os }}-${{ hashFiles('**/setup_gcc.sh') }}
    #     restore-keys: |
    #       gcc-${{ inputs.gcc-version }}-${{ inputs.os }}-

    - name: install gcc ${{ inputs.gcc-version }}
      shell: bash
      run: |
        ls .
        pwd
        
        wget https://ftp.gnu.org/gnu/gcc/gcc-${{ inputs.gcc-version }}/gcc-${{ inputs.gcc-version }}.tar.gz > /dev/null 2>&1
        
        # tar -xvf gcc-${{ inputs.gcc-version }}.tar.gz > /dev/null 2>&1

        # cd gcc-${{ inputs.gcc-version }}
        # pwd

        # ./contrib/download_prerequisites > /dev/null

        # ./configure --enable-languages=c,c++ --disable-multilib --with-system-zlib --prefix=$HOME/usr/local/gcc-${{ inputs.gcc-version }}

        # make -j$(nproc)
        # make install
