name: dynamic-save
description: uses save action with older version of node depending on OS used

inputs:
  OS: 
    required: true
  path:
    required: true
  key:
    required: true
  
  
runs:
  using: 'composite'
  

  - if: ${{ contains(fromJson('["ubuntu:18.04"]'), matrix.OS) }}
    name: save v3
    uses: actions/cache/save@v3
    with:
      path: ${{ inputs.path }}
      key: ${{ inputs.key}}
  
  # else use checkout v4
  - if: ${{ !contains(fromJson('["ubuntu:18.04"]'), matrix.OS)  }}
    name: save v4
    uses: actions/cache/save@v4
    with:
      path: ${{ inputs.path }}
      key: ${{ inputs.key}}