name: setup armclang
description: installs dependencies and correct armclang version to build and test simeng

inputs:
  OS:
    required: true
  LLVM-VERSION:
    required: true
  COMPILER: 
    required: true

runs:
  using: 'composite'
  steps:
    ##########################################
    # GCC jobs
    ##########################################

    # ubuntu
    - if: ${{ contains( inputs.COMPILER, 'gcc') && contains( inputs.OS, 'ubuntu') }}
      name:  Install ${{ inputs.COMPILER }} + Build SimEng
      uses: ./.github/actions/setup_gcc_ubuntu
      with:
        LLVM-VERSION: ${{ inputs.LLVM-VERSION }}
        OS: ${{ inputs.OS }}
        gcc-version: ${{ inputs.COMPILER }}
    
    # rocky linux
    - if: ${{ contains( inputs.COMPILER, 'gcc') && contains( inputs.OS, 'rocky') }}
      name:  Install ${{ inputs.COMPILER }} + Build SimEng
      uses: ./.github/actions/setup_gcc_rocky
      with:
        LLVM-VERSION: ${{ inputs.LLVM-VERSION }}
        OS: ${{ inputs.OS }}
        gcc-version: ${{ inputs.COMPILER }}

    ##########################################
    # ARMCLANG jobs
    ##########################################
    - if: ${{ contains( inputs.COMPILER, 'armclang') && contains(inputs.OS, 'ubuntu') }}
      name:  Install ${{ inputs.COMPILER }} + Build SimEng
      uses: ./.github/actions/setup_armclang_ubuntu
      with:
        LLVM-VERSION: ${{ inputs.LLVM-VERSION }}
        OS: ${{ inputs.OS }}
    
