name: setup cmake
description: installs and caches cmake

inputs:
  OS:
    required: true

runs:
  using: 'composite'
  steps:
  
    - if: ${{ inputs.OS == 'ubuntu:18.04' }}
      name: install cmake via apt
      shell: bash
      run: |
        apt-get update && \
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null && \
        apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' && \
        apt update && apt install cmake -y

    - if: ${{ inputs.OS == 'ubuntu:20.04' }}
      name: install cmake via apt
      shell: bash
      run: |
        apt-get update && \
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null && \
        apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main' && \
        apt update && apt install cmake -y

    # #######################################
    # # This section sets up cmake and handles caching
    # #######################################
    # # check cache for cmake
    # - if: ${{ inputs.OS == 'ubuntu:18.04' }}
    #   name: cmake restore
    #   id: cmake-restore-v3
    #   uses: actions/cache/restore@v3
    #   with:
    #     path: |
    #       /usr/local/bin/cmake
    #       /usr/local/bin/ctest
    #       /usr/local/share/cmake-3.29
    #     key: cmake-${{ matrix.OS }}

    # - if: ${{ inputs.OS == 'ubuntu:20.04' }}
    #   name: cmake restore
    #   id: cmake-restore-v4
    #   uses: actions/cache/restore@v4
    #   with:
    #     path: |
    #       /usr/local/bin/cmake
    #       /usr/local/bin/ctest
    #       /usr/local/share/cmake-3.25
    #     key: cmake-${{ matrix.OS }}
    # ######################################
    # # install cmake if cache miss
    # - if: ${{ steps.cmake-restore-v3.outputs.cache-hit != 'true' && steps.cmake-restore-v4.outputs.cache-hit != 'true' }}
    # - name: install cmake
    #   shell: bash
    #   run: |
    #     wget https://github.com/Kitware/CMake/releases/download/v3.16.3/cmake-3.16.3.tar.gz
    #     tar zxvf cmake-3.16.3.tar.gz
    #     cd cmake-3.16.3
    #     ./bootstrap
    #     make
    #     make install
    # ######################################
    # # save to cmake to cache if cache miss
    # - if: ${{ steps.cmake-restore-v3.outputs.cache-hit != 'true' && inputs.OS == 'ubuntu:18.04'}}
    #   name: cmake save
    #   id: cmake-save-v3
    #   uses: actions/cache/save@v3
    #   with:
    #     path: |
    #       /usr/local/bin/cmake
    #       /usr/local/bin/ctest
    #       /usr/local/share/cmake-3.29
    #     key: cmake-${{ matrix.OS }}

    # - if: ${{ steps.cmake-restore-v4.outputs.cache-hit != 'true' && inputs.OS == 'ubuntu:20.04'}}
    #   name: cmake save
    #   id: cmake-save-v4
    #   uses: actions/cache/save@v4
    #   with:
    #     path: |
    #       /usr/local/bin/cmake
    #       /usr/local/bin/ctest
    #       /usr/local/share/cmake-3.25
    #     key: cmake-${{ matrix.OS }}
    # ######################################
