# changes version of checkout based on OS 
# github has depreciated older versions of node hence we have to use the older version of actions for older OS with older node versions e.g. ubuntu 18.04

name: dynamic-checkout

inputs:
  OS:
    required: true

runs:
  using: 'composite'
  steps:

    # if input is in list of OS that use older node versions, use checkout v3
    - if: ${{ contains(fromJson('["ubuntu:18.04"]'), inputs.OS) }}
      name: checkout v3
      uses: actions/checkout@v3
    
    # else use checkout v4
    - if: ${{ !contains(fromJson('["ubuntu:18.04"]'), inputs.OS)  }}
      name: checkout v4
      uses: actions/checkout@v4
