name: sets up dependencies for simeng 

inputs:

  OS:
    required: true

runs:
  using: 'composite'
  steps:
    #######################################
    # install dependencies I think are required to build simeng
    #######################################
    - if: contains(${{ inputs.OS }}, 'ubuntu')
      name: install dependencies
      shell: bash
      run: |
        export DEBIAN_FRONTEND=noninteractive
        
        apt-get update

        apt-get install -y sudo
        apt-get install -y wget
        apt-get install -y zlib1g-dev
        apt-get install -y python3
        apt install -y build-essential
        apt install -y git
        apt-get install libssl-dev
        apt-get install ninja-build

        apt-get install -y software-properties-common


        apt-get update
        apt-get upgrade -y