name: OS + Compiler checks

# workflow triggers
on:
  workflow_dispatch:
  pull_request:


jobs:

  Build_and_Run:

    strategy:
      matrix: 
        OS: ["ubuntu:20.04"] # ["ubuntu:20.04", "debian:12.4", "centos:7", "redhat/ubi8", "rockylinux:9.3", "linuxmintd/mint21.2-amd64"]
        Compilers: [gcc-7.3.0, gcc-9.3.0, gcc-10.3.0] # [gcc-7.3.0, gcc-9.3.0, gcc-10.3.0]
        
        # We remove the combination (ubuntu:20.04, gcc-7.3.0) because ubuntu versions above 18.04 are missing some depreciated files required for gcc 7.3.0 to run
        # We replace (ubuntu:20.04, gcc-7.3.0) with (ubuntu:18.04, gcc-7.3.0)
        exclude:
          - OS: "ubuntu:20.04"
            Compilers: gcc-7.3.0
        include:
          - OS: "ubuntu:18.04"
            Compilers: gcc- 7.3.0
    
    runs-on: ubuntu-latest

    container: 
      image: ${{ matrix.OS }}
      volumes:
        - ${{ github.workspace }}:/simeng
    
    name: ${{ matrix.OS }} + ${{ matrix.Compilers }}
    steps:
      - name: test
        run: |
          echo "working"
          cat /etc/os-release
          ls

      # - name: build compiler from source
      #   uses: setup
      #   with:
          

      
      